[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm ci --production"]

[phases.build]
cmds = ["echo 'No build step needed for backend-only deployment'"]

[start]
cmd = "cd server && node railway-start.js"