[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "cd server",
  "npm ci --production --silent"
]

[phases.build]
cmds = ["echo 'Backend-only deployment - no build step required'"]

[start]
cmd = "cd server && node railway-start.js"

[variables]
NODE_ENV = "production"