[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"